### ISSUE TITLE
configtxgen: command not found

### ISSUE THREAD

**Issue by piroti** [MD-AZMAL/Energy-Blocks-App#1]
when I run "./generateArtifacts" it runs, but frequently gives error for configtxgen and says that "command not found". @MD-AZMAL @shubhsherl 
![error](https://user-images.githubusercontent.com/24540134/62572372-38de1c00-b89c-11e9-9df3-885f39887bbb.png)

**Comment by shubhsherl** [comment]
@piroti make sure that `fabric-samples/bin` is in your env path.

**Comment by piroti** [comment]
@shubhsherl  shall I copy/paste files of fabric-samples/bin in "/artifacts/channel" directory? or what?

**Comment by shubhsherl** [comment]
https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html#run-the-tools
We are using the script to generate the config file. It should be mentioned in the docs, we will add it.
You can copy/paste the files, it will work.
@piroti

**Comment by piroti** [comment]
@shubhsherl I did, but still not solved. plase guide me step-by-step. I really interested to run your code.

**Comment by MD-AZMAL** [comment]
@prioti make sure you have them as excitable. for example chmod +x script.sh

**Comment by shubhsherl** [comment]
@prioti are you able to run the script? As @md-azmal said make sure every script has executable permission.

**Comment by piroti** [comment]
Yes, all are executable, but there are problems with both "./generateartifacts" and "./runContainers". docker ps gives empty list.

**Comment by shubhsherl** [comment]
Can you post the log of docker container if there is any container in `docker ps -a` or any other log errors.

**Comment by piroti** [comment]
check you yahoo email please
